### ISSUE TITLE
Automatic deployment - never go back in time [3h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-starter#138]
Right now it's possible that automatic deployment reverts already deployed changes.
Deployment jobs might be created like this:
Job A
Job B

But executed in this order:
Job B
Job A

Then changes from Job B are reverted essentially.
To prevent that, we could store the timestamp of the Git commit in the artifact repository to ensure that we never deploy outdated code.

**Comment by AronNovak** [comment]
@amitaibu 
What if we solve this by enabling auto-cancellation of jobs in Travis.
https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation - we could do it per-branch, for all the branches with auto-deploy, if we activate it, it will never happen again that an older state of the source code gets deployed later than a newer one.
This way we do not need to change anything in the deployment code and we'd eliminate this race condition at another place.

//cc @mariano-dagostino

**Comment by amitaibu** [comment]
Sure, let's use that.

Although I suspect you might still have a race condition, if let's say a newer build start after an previous one has already started; and for some reason the new build is faster.

Anyway, for now I think we can try the auto-cancellation

**Comment by AronNovak** [comment]
> Auto Cancellation allows you to only run builds for the latest commits in the queue. This setting can be applied to builds for Branch builds and Pull Request builds separately. Builds will only be canceled if they are waiting to run, allowing for any running jobs to finish. 

You're right, it's not the perfect solution.

**Comment by AronNovak** [comment]
@amitaibu 
Here's another plan:
 - GH repo: Get `git rev-parse HEAD` - get hash of the current deployment
 - Artifact repo: store the hash in a metadata file, like .deployment
 - Abort the process if the hash in .deployment isn't in the GH Git history

If things go well, commit A, B, C gets deployed sequentially, when B is deployed, hash A is in the Git history.
If things are screwed, A, B, C gets deployed in a random order, let's say B, C, A, the last one would be aborted as hash of "C" is not in the history of the working copy of A.

**Comment by amitaibu** [comment]
Sounds good

**Comment by ordavidil** [comment]
@AronNovak 

I suspect that we still face a race condition with the current solution:

1. Job A cloning Pantheon's repo (invoked by https://github.com/Gizra/drupal-starter/blob/master/.travis.yml#L69)
2. Job B cloning Pantheon's repo (invoked by https://github.com/Gizra/drupal-starter/blob/master/.travis.yml#L69), before Job A is managed to push and sync its code with the updated `.deployment` (which is invoked by https://github.com/Gizra/drupal-starter/blob/master/.travis.yml#L70)

Now we have two jobs, with the same `.deployment` hash, so we're back at  https://github.com/Gizra/drupal-starter/issues/138#issuecomment-788878836
(this is a real use case which happens pretty often when you merge multiple PRs within a gap of a few seconds).

I think that in order to fix it, we can somehow try to implement some kind of a semaphore (maybe some variable we can store in travis?) :man_shrugging: 

//cc @amitaibu

**Comment by AronNovak** [comment]
@ordavidil It's a very good point.
I think we could use what @mariano-dagostino introduced at one project - deployment mode. And we set deployment mode at the very beginning, query before / after, and abort the process if the deployment mode was already set. This reduces the critical path to sub-second length.

//cc @amitaibu

**Comment by AronNovak** [comment]
Or alternatively we treat it as an edge case now and return back if we'll have a real occurrence of the problem.

**Comment by ordavidil** [comment]
> Or alternatively we treat it as an edge case now and return back if we'll have a real occurrence of the problem.

I tend to say that merging multiple PRs in few seconds is not an edge case, but maybe it's only me :man_shrugging:
