### ISSUE TITLE
`sudo` errors on Gitpod

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#214]
![Selection_999(450)](https://user-images.githubusercontent.com/125707/141187249-e8cce37e-d336-4102-a751-c25208641a21.jpg)

Not sure if it has any meaning in our case? (Site is still installed properly in the end of the process)

**Comment by AronNovak** [comment]
![image](https://user-images.githubusercontent.com/114076/141256698-17cf420e-1e12-4cf3-876c-4b745303bfdc.png)
We inherited this from `ddev-gitpod`, let me see if we can address this.

**Comment by AronNovak** [comment]
@amitaibu The issue is that Kubernetes mounts `/etc/hosts` separately, read-only:
![image](https://user-images.githubusercontent.com/114076/141259439-fa88ce0e-45b7-4ac9-9dd6-9dd9b7f80665.png)
And DDEV of course tries to update it, so this warning is specific to GitPod environment and we can't do much about it, I'd leave it as-is.
